= Saída de comando "storage failover show" inesperada
:allow-uri-read: 


Alguns problemas podem ocorrer durante diferentes fases do procedimento.



== Saída de comando "storage failover show" inesperada

Durante o procedimento, se o nó que hospeda todos os dados agrega panics ou for reiniciado acidentalmente, você poderá ver saída inesperada para o `storage failover show` comando antes e depois do ciclo de reinicialização, pânico ou energia.

.Sobre esta tarefa
Você pode ver uma saída inesperada do `storage failover show` comando no Estágio 2, Estágio 3, Estágio 4 ou Estágio 5.

O exemplo a seguir mostra a saída esperada `storage failover show` do comando se não houver reinicializações ou panics no nó que hospeda todos os agregados de dados:

....
cluster::> storage failover show

                   Takeover
Node     Partner   Possible  State Description
-------  --------  --------- -----------------
node1    node2     false     Unknown
node2    node1     false     Node owns partner aggregates as part of the non-disruptive head upgrade procedure. Takeover is not possible: Storage failover is disabled.
....
O exemplo a seguir mostra a saída `storage failover show` do comando após uma reinicialização ou pânico:

....
cluster::> storage failover show

                   Takeover
Node     Partner   Possible  State Description
-------  --------  --------- -----------------
node1    node2     -         Unknown
node2    node1     false     Waiting for node1, Partial giveback, Takeover is not possible: Storage failover is disabled
....
Embora a saída diga que um nó está em giveback parcial e que o failover de armazenamento está desativado, você pode ignorar essa mensagem.

.Passos
Nenhuma ação é necessária; continue com o procedimento de atualização do par de nós.
